"""
Cone Example

This example demonstrates rendering a 3D cone using VTK.js Algorithm
component with the vtkConeSource.

Run with: python examples/cone.py
Then open: http://localhost:8000
"""

from fastapi import FastAPI

from refast import Context, RefastApp
from refast.components import Container, Heading, Text
from refast_vtk_js import (
    Algorithm,
    GeometryRepresentation,
    View,
)

# Create the Refast app with VTK extension
ui = RefastApp(
    title="VTK.js Cone",
)


@ui.page("/")
def home(ctx: Context):
    """Home page with a 3D cone visualization."""
    return Container(
        class_name="p-4 max-w-4xl mx-auto",
        children=[
            Heading("VTK.js 3D Cone", level=1, class_name="mb-4"),
            Text(
                "This example demonstrates using the Algorithm component "
                "with vtkConeSource to generate a 3D cone.",
                class_name="mb-4 text-muted-foreground",
            ),
            View(
                background=[0.9, 0.9, 1.0],
                style={"width": "100%", "height": "400px"},
                children=[
                    GeometryRepresentation(
                        property={
                            "color": [0.2, 0.6, 0.9],  # Blue color
                            "edgeVisibility": True,
                            "edgeColor": [1, 1, 1],
                            "opacity": 1.0,
                        },
                        children=[
                            Algorithm(
                                vtk_class="vtkConeSource",
                                state={
                                    "resolution": 32,  # Smooth cone
                                    "radius": 0.5,
                                    "height": 1.0,
                                    "capping": True,
                                },
                            )
                        ],
                    )
                ],
            ),
            Text(
                "The cone is generated by vtkConeSource with 32 resolution segments.",
                class_name="mt-2 text-sm text-muted-foreground",
            ),
        ],
    )


# Create FastAPI app
app = FastAPI(title="VTK.js Cone Demo")
app.include_router(ui.router)

if __name__ == "__main__":
    import uvicorn

    print("Starting VTK.js Cone Demo...")
    print("Open http://localhost:8000 in your browser")
    uvicorn.run(app, host="0.0.0.0", port=8000)
